<a href="https://colab.research.google.com/github/SAIFUL700-WQ/saiful/blob/main/10th_class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
#print(type(arr))

[1 2 3 4 5]


In [6]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:

import numpy as np

zeros = np.zeros((2, 3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
zeros = np.zeros((2, 3, 2))
print(zeros)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [13]:
zeros = np.zeros((3))
print(zeros)

[0. 0. 0.]


In [14]:
ones = np.ones((2, 3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
zeros = np.zeros((3, 3))
ones = np.ones((2, 4))
arange = np.arange(0, 10 , 2)
linspace = np.linspace(0, 1, 5)
print(zeros)
print(ones)
print(arange)
print(linspace)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [19]:
arange = np.arange(1, 10 , 2)
print(arange)

[1 3 5 7 9]


In [18]:
linspace = np.linspace(0, 10, 5)
print(linspace)

[ 0.   2.5  5.   7.5 10. ]


In [20]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])
print(arr[2])
print (arr[-1])

10
30
50


In [23]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d[0,0])
print(arr_2d[1,2])
print(arr_2d[2,-1])

1
6
9


In [26]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d[1:4, 0:2])

[[4 5]
 [7 8]]


In [32]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d[:, 0])
print(arr_2d[0, 1])
print(arr_2d[1:, 0:1])
print(arr_2d[:, 0:1])

[1 4 7]
2
[[4]
 [7]]
[[1]
 [4]
 [7]]


In [33]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print (arr1 + arr2)
print (arr1 - arr2)
print (arr1 * arr2)
print (arr1 / arr2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [34]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print (arr1 + arr2)
print (arr1 - arr2)
print (arr1 + 10)


[5 7 9]
[-3 -3 -3]
[11 12 13]


In [38]:
arr1 = np.array([[1, 2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
print (np.dot(arr1,arr2))


[[19 22]
 [43 50]]


In [40]:
arr = np.array([1, 2, 3, 4, 5])
print(np.mean(arr)) #mean
print(np.std(arr))  #standrd daviation
print(np.sum(arr))  #sum
print(np.min(arr))  #min
print(np.max(arr))  #max
print(np.median(arr)) #median

3.0
1.4142135623730951
15
1
5
3.0


In [48]:
arr = np.arange(1,13)
arr_reshaped = arr.reshape(3,4)
print(arr_reshaped)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [49]:
arr = np.arange(1,13)
arr_reshaped = arr.reshape(3,4)
arr_reshaped_2 = arr.reshape(4,3)
print(arr_reshaped)
print(arr_reshaped_2)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [50]:
print(arr_reshaped.flatten()) #flatten multi dimension to one dimension

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [56]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
print(np.concatenate((arr1,arr2),axis=0))
print(np.concatenate((arr1,arr2),axis=1))
#print(np.concatenate((arr1,arr2),axis=2))  axis 2 nai tai erron asbe


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
